server:
  port: 8080

spring:
  application:
    name: sistema-saude
  data:
    mongodb:
      uri: mongodb://localhost:27017/sistema-saude
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false